### ISSUE TITLE
Blank screen on opening BPMN20.xml on vscode for mac

### ISSUE THREAD

**Issue by srikanthjr02** [bpmn-io/vs-code-bpmn-io#103]
__Describe the Bug__

Unable to view any thing (blank screen) on opening an existing bpmn flow (bpmn20.xml) in vscode using bpmn.io plugin in vscode for mac 

__Steps to Reproduce__

1. find an existing XXXXXXX.bpmn20.xml 
2. Open by right clicking or from the icon on the top right corner on vscode running in macos 
3. All you find is a blank white screen - model is not visible

__Expected Behavior__

__Environment__

- Host (Browser/Node version), if applicable: Visual studio code
- OS: macos monterey / macos big sur 
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment]
I was not able to reproduce this with [an example diagram](https://github.com/bpmn-io/vs-code-bpmn-io/files/7601582/diagram.bpmn20.xml.txt) (remove `.txt` to use it, GitHub does not allow `.xml` files to be attached to issues)

![Kapture 2021-11-25 at 10 01 32](https://user-images.githubusercontent.com/9433996/143411275-abc7b2bd-f849-48bd-a7b0-c92fd79e111b.gif)

Can you maybe share
* the `bpmn-io-vs-code` extension version you are using
* the diagram you try to open in the editor
* any existing `.xml` related VS Code extension you're using

The third question is related [to problems we had in the past](https://github.com/bpmn-io/vs-code-bpmn-io/issues/96#issuecomment-839514257) with other extensions.

**Comment by pinussilvestrus** [comment]
@srikanthjr02 anything you can add to this one? Without the necessary information, it will be hard to reproduce your problem.

**Comment by pinussilvestrus** [comment]
Closed due to inactivity. Feel free to re-open once you can [provide more information](https://github.com/bpmn-io/vs-code-bpmn-io/issues/103#issuecomment-978987107).
