### ISSUE TITLE
VSCode shows empty page after update

### ISSUE THREAD

**Issue by tom-inetum-realdolmen** [bpmn-io/vs-code-bpmn-io#108]
__Describe the Bug__

I created a diagram via your extension and saved. When I close and reopen the file in bpm.io editor everything is visible.

However when I made changes to parts of the process, save and close the diagram, I get a blank screen in vscode bpmn.io extension rather than my (updated) diagram.

If I open the latest revision on the website https://demo.bpmn.io, my process is clearly visible and editable.

more info: if you add `<bpmn2:text>` to your diagram and they contain a single quote `'`, the diagram will no longer be visible via vscode.

__Steps to Reproduce__

1. Open old version of the attached process in vscode extension => diagram is visible
2. Open new version of the attached process in vscode extension => white page
3. Open the new version of the process and remove the quote on position 178:53 ==> diagram is visible again

__Expected Behavior__

I would like to see the diagram in your extension and not have to go to demo.bpmn.io

__Environment__

- Host (Browser/Node version), if applicable: VSCode 1.70.1 with BPMN.io Editor extension v0.13.0 (updated on 11 april 2022)
- OS: Windows 10 21H2
- Library version: N/A

[old-new-bpmnfile.zip](https://github.com/bpmn-io/vs-code-bpmn-io/files/9673281/old-new-bpmnfile.zip)

**Comment by tom-inetum-realdolmen** [comment]
When text is added to the `<bpmn2:text>`, 'special' tags like `'` and `"` are not replaced by `&apos;` and `&quot;` respectively. However `<` and `>` are being replaced by `&lt;` and `&gt;` on save.

**Comment by pinussilvestrus** [comment]
Thanks for reporting and sharing your diagrams! 

> However when I made changes to parts of the process, save and close the diagram,

Did you make the changes inside the VS Code extension or somewhere else?

> When text is added to the `<bpmn2:text>`, 'special' tags like `'` and `"` are not replaced by `&apos;` and `&quot;` respectively. However `<` and `>` are being replaced by `&lt;` and `&gt;` on save.

Thanks for the hint. It could be that the extension is not properly parsing the XML. We have a similar issue with script (cf. https://github.com/bpmn-io/vs-code-bpmn-io/issues/99).

**Comment by tom-inetum-realdolmen** [comment]
> Did you make the changes inside the VS Code extension or somewhere else?

Yes I did. You can continue editing the diagram until you close it and then it doesn't reopen. I think the dependend bpmn-js version (9.0.3) might be a bit outdated...

**Comment by pinussilvestrus** [comment]
Thanks for the update! I will move this to backlog as this is not a priority. Marking it as spring cleaning so we could handle this in our upcoming spring cleaning week.

We are open to contribution that improve the situation (especially in doing the bpmn-js update) 👍

**Comment by pinussilvestrus** [comment]
This is fixed via `v0.14.0`. Feel free to re-open once you see any other related issues!
