### ISSUE TITLE
VSCode Extension, can't create diagram

### ISSUE THREAD

**Issue by matonb** [bpmn-io/vs-code-bpmn-io#117]
### Describe the Bug

Cannot add any symbols to a new (empty) bpmn diagram
The canvas turns pink and the cursor becomes a 'no entry' :no_entry_sign:

### Steps to Reproduce

1. Create a new document `file.bpmn`
2. Enable bpmn view (ctrl-shift-v)
3. Drag start symbol on to document

### Expected Behaviour

To be able to draw a diagram

### Environment

| Component | Version |
| --- | ---: |
| BPMN.io VSCode extension | v0.14.0 |
| VSCode | 1.78.2 |
| Electron | 22.5.2 |
| Chromium | 108.0.5359.215 |
| Node.js | 16.17.1 |
| V8 | 10.8.168.25-electron.0 |
| OS - Windows | 11 |

**Comment by smbea** [comment]
I transfered this issue to the according vscode extension repository

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/vs-code-bpmn-io/commit/91c5d1c9c7e0762c684640c1643416e9c8fdbde5.
