### ISSUE TITLE
"Save as..." causes unexpected error: document already exists

### ISSUE THREAD

**Issue by huddeldaddel** [bpmn-io/vs-code-bpmn-io#176]
### Describe the Bug

Saving diagram in new location causes error message. The diagram file can not be loaded until Visual Studio Code is restarted.

### Steps to Reproduce

1. Open a ".bpmn" file in VSCode with BPMN.io Editor Plugin
2. Use menu option "Save As" to save file in new location
4. Now VS Code displays message: "The editor could not be opened due to an unexpected error: document alreasy exists"

### Expected Behavior

Common behavior would be that VSCode would display the file (from new location).

### Environment

- Visual Studio Code 1.93.1 (user setup)
- OS: Windows 10
- Electron: 30.4.0
- Chromium: 124.0.6367.243
- Node: 20.15.1
- Plugin version: bpmn-io.vs-code-bpmn-io v0.21.2

**Comment by barmac** [comment]
I can reproduce this issue. Thanks for reporting.

**Comment by barmac** [comment]
We are happy to accept external contributions. Would you like to provide a fix?

**Comment by huddeldaddel** [comment]
I'll give it a try. I've never worked on VS plugins before - but it sounds like a nice challenge.
