### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by salaboy** [bpmn-io/vs-code-bpmn-io#21]
## Features to have | Bugs to fix

* [ ] Properties Panel Support #20 
* [ ] optional: Add dirty indicator https://github.com/pinussilvestrus/vs-code-bpmn-io/issues/48

## Further Tasks

* [ ] Update [`CHANGELOG`](https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/blob/master/CHANGELOG.md)
* [ ] Release to marketplace

**Comment by salaboy** [comment]
@pinussilvestrus let's work together into prioritising this release

**Comment by pinussilvestrus** [comment]
Jep, let's do this 🚀

Furthermore: I added an issue template for the release tickets we can use in the future: https://github.com/pinussilvestrus/vs-code-bpmn-io/issues/new?assignees=&labels=release&template=release-template.md&title=Release+%5Bnumber%5D

**Comment by pinussilvestrus** [comment]
We should plan releases once we decided what to build next.
