### ISSUE TITLE
Transform under bpmn.io sphere

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/vs-code-bpmn-io#49]
Currently, this project and the [marketplace entry](https://marketplace.visualstudio.com/items?itemName=salaboy.vs-code-bpmn-io) does not go under the `bpmn-io` organization. We should change this. This would include

* [x] Add proper setup instructions
* [x] Remove `dependabot` dependency
* [x] Add release documentation
* [x] Use `bpmn-io eslint config` under `tslint` 
* [x] Add test infrastructure, cf. #10 
* [x] Remove unrelated / wip stuff
* [x] Change ownership of GitHub repository to bpmn-io
   * rename to `bpmn-io/vs-code-plugin` ?
* [x] Change ownership in VS Code Marketplace (create Azure DevOps organization first)
   * Use `bpmnio@camunda.com` as username
   * Create publisher and access token, cf. [release docs](https://github.com/pinussilvestrus/vs-code-bpmn-io/blob/master/docs/RELEASING.md)
* [x] Update Metadata for publishing, cf. https://github.com/pinussilvestrus/vs-code-bpmn-io/blob/master/package.json#L7
* [x] Add Logo in Marketplace entry, cf. #15 
* [x] Release new Version to Marketplace

**Comment by pinussilvestrus** [comment]
Requirements to transform into `bpmn-io` should be satisfied now. Let's do the last steps together when we're back from Holiday @nikku.

**Comment by nikku** [comment]
:christmas_tree:
