### ISSUE TITLE
Can not change type

### ISSUE THREAD

**Issue by DarioCalovic** [bpmn-io/vs-code-bpmn-io#65]
__Describe the Bug__

Some controls do not work withing the modeler. For instance you can not change a type of a task or a gateway. The controls are even shown slightly transparent. Same transparent behaviour you get, when you rename a element.

__Steps to Reproduce__

1. Open a BPMN diagram
2. Click on Edit
3. Click on a task (first behaviour: the controls appear transparent)
4. Click on the settings icon and try to change to a type by clicking on it
5. Nothing happens

Developer Tools prints: `Uncaught ReferenceError: parent is not defined`

__Expected Behavior__

The control buttons should not be transparent and the type should have been changed.

__Environment__

- OS: Windows 10 and Ubuntu 18
- VSCode: 1.42.1
- BPMN Extension: v0.6.4

**Comment by nikku** [comment]
Both bugs will be fixed with next release :cactus:.
