### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by nikku** [bpmn-io/vs-code-bpmn-io#66]
__What is inside__

* [x] Only offer BPMN Editor as an extension action
* [x] Fix broken editor capabilities, cf. https://github.com/bpmn-io/vs-code-bpmn-io/issues/65, https://github.com/bpmn-io/vs-code-bpmn-io/issues/59

**Comment by pinussilvestrus** [comment]
#59 inside one editor got fixed by the bpmn-js update
