### ISSUE TITLE
Support for .bpmn2 extension

### ISSUE THREAD

**Issue by celsogg** [bpmn-io/vs-code-bpmn-io#78]
jBPM produces .bpmn2 files, changing it to .bpmn opens the diagram correctly, it would be nice if be possible to open files wihout change it.

**Comment by pinussilvestrus** [comment]
This has to go inside the [extension configuration](https://github.com/bpmn-io/vs-code-bpmn-io/blob/master/package.json#L30).

We're open for contributions 👍
