### ISSUE TITLE
Creation of a BPMN diagram without any elements when opening an empty BPMN file

### ISSUE THREAD

**Issue by ElCondor1969** [bpmn-io/vs-code-bpmn-io#85]
__Is your feature request related to a problem? Please describe__

The BPMN editor does nothing when it displays an empty BPMN file.
This is not a bug but a little issue in user experience.

__Describe the solution you'd like__

Suppose you open an empty BPMN file in VS Code, meaning that the file is zero bytes sized.
Opening the BPMN preview of this file, the extension should ask the user if he wants to create an empty BPMN diagram, that is an XML file formally corrected to be a valid BPMN file, but which does not contain any graphic elements inside it.
This feature is very useful to edit a new BPMN diagram without starting from an existing valid BPMN file.

__Describe alternatives you've considered__

I have not a valid alternative.

__Additional context__

None

**Comment by pinussilvestrus** [comment]
Cool idea 👍 Could you update the issue description to [fit into our issue schema](https://github.com/bpmn-io/vs-code-bpmn-io/issues/new?labels=enhancement&template=FEATURE_REQUEST.md)?

**Comment by ElCondor1969** [comment]
I just did it @pinussilvestrus.
I hope I did it right.

**Comment by pinussilvestrus** [comment]
`spring cleaning` is a label we use internally for project management purposes. Since this issue is in `backlog` we don't have plans to work on it soon.
