### ISSUE TITLE
Add BPMN lint

### ISSUE THREAD

**Issue by thirtytwobits** [bpmn-io/vs-code-bpmn-io#86]
Please add https://github.com/bpmn-io/bpmn-js-bpmnlint to the extension.

**Comment by pinussilvestrus** [comment]
Can you please use our [issue template](https://github.com/bpmn-io/vs-code-bpmn-io/issues/new?labels=enhancement&template=FEATURE_REQUEST.md)?

**Comment by philippfromme** [comment]
Why should we do this?

**Comment by pinussilvestrus** [comment]
Without extra knowledge, it's hard to find out why it's necessary to have this plugin in the VS Code extension. Feel free to re-open the issue if you have further insights.
