### ISSUE TITLE
Support ability to set colors

### ISSUE THREAD

**Issue by vkatushenok** [bpmn-io/vs-code-bpmn-io#93]
__Is your feature request related to a problem? Please describe__

Continuing work on existing diagrams that use colors (e.g. set via Cawemo or Camunda Modeler) is not fully possible.

__Describe the solution you'd like__

Would be great to bring palette of at least same x6 colors used across BPMN.io based tools.
As a minimal and flexible setup, palette / "colorize" could be an extension option in a format of CSS supported `string` array with defaults already pre-set

Feature description & example: https://bpmn.io/blog/posts/2016-colors-bpmn-js.html

![image](https://user-images.githubusercontent.com/2331533/112964953-848db980-9194-11eb-9424-71ab4357c2de.png)

**Comment by pinussilvestrus** [comment]
Thanks for reporting 👍

**Comment by vkatushenok** [comment]
> Hi @vkatushenok 👋🏻, nice to see that after all this time you still care about BPMN. 💟

Haha, I still strongly believe in process automation and BPMN(.io) is still the best tool to model those 😉 .

**Comment by smbea** [comment]
Closing as duplicate as this is being tracked with https://github.com/bpmn-io/bpmn-js/issues/1491.

**Comment by pinussilvestrus** [comment]
Still, we will need a bpmn-js bump to make it work (which is not automated by now).

**Comment by smbea** [comment]
re-opened and linked it in the other issue. We can mark it as `fixed-upstream` to be updated when the feature is merged.

**Comment by tpucci** [comment]
Hello there,
I would be interested to have that feature in the extension 🙂 do you accept new contributors and PRs ?

**Comment by philippfromme** [comment]
@tpucci Yes, we very much welcome contributions! Feel free to pick this up and ask questions.

**Comment by tpucci** [comment]
> @tpucci Yes, we very much welcome contributions! Feel free to pick this up and ask questions.

Great ! I will try to add this feature in the coming days.

I assume this ability would be opted-in, isn't it ?
Should we add a `"bpmn-js.additionalModules": ["color-picker"]` user setting ?

**Comment by philippfromme** [comment]
@tpucci I personally don't think it's necessary to make the color picker opt-in. It's just one additional entry in the context pad and users can simply ignore it.

**Comment by tpucci** [comment]
I created a PR #145. Let's continue the discussion there 👍

**Comment by tpucci** [comment]
Hi @philippfromme, PR #145 is ready to be merged. Can you review it ? 🙂
